---
title: "gapminder"
author: "DaveK"
date: "March 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Tidyverse
```{r}
library(tidyverse)
```

## gapminder dataset
```{r}
gapminder <- read_csv("https://raw.githubusercontent.com/jules32/2017-11-30-MBARI/gh-pages/data/gapminder.csv")
```
```{r}
head(gapminder, 2)
tail(gapminder, 10)
```
```{r}
str(gapminder)
```

```{r}
dim(gapminder)
ncol(gapminder)
nrow(gapminder)
```

```{r {}
unique(gapminder[,"continent"])
unique(gapminder$continent)
```

```{r}
summary(gapminder)
```
## skimr
```{r}
## install.packages("skimr")
library(skimr)
skim(gapminder)
```

## dplyr
```{r}
dplyr::filter(gapminder, country == "Switzerland")
```
### filter
```{r}
dplyr::filter(gapminder, country =="Afghanistan", year == max(year))
```
### select
```{r}
dplyr::select(gapminder, country, year, pop)
```

```{r}
dplyr::select(gapminder, -continent)
```
## select
```{r}
gapminder_no_cont <- dplyr::select(gapminder, -continent)
dplyr::filter(gapminder_no_cont, year == 2007)
```

```{r}
## example of pipe in R ( %>% )
select(gapminder, -continent) %>% filter(year == 2007)

```

```{r}
gapminder %>% mutate(gdp = gdpPercap * pop) %>% arrange(desc(gdp))
```

```{r}
library(tidyverse)
gapminder %>% group_by(country) %>% mutate(gdp = gdpPercap * pop, max_gdp = max(gdp)) %>% ungroup()
```

```{r}
gapminder %>% group_by(country) %>% mutate(gdp = pop * gdpPercap) %>% summarize(max_gdp = max(gdp))
```

```{r}
co2 <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")
```

```{r}
head(co2)
summary(co2)
```
```{r}
gap_2007 <- gapminder %>% filter(year == 2007)
```

```{r}
right_join(gap_2007, co2, by="country")
```
```{r}
AirPassengers
```

```{r}
tidyr::gather(as.data.frame(AirPassengers), month, passenger)
```

```{r}
gap_wide <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv")
```

```{r}
gap_better <- gap_wide %>% gather(observation, observ_value, -continent, -country) %>% 
  separate(observation, into=c("obs_type", "year"), sep='_', convert=TRUE)
```

```{r}
unique(gap_better$obs_type)
```
```{r}
gap_better %>% spread(obs_type, observ_value)
```

